### ISSUE TITLE
Example file doesn't work (bad destination `~a' "~A.~A")

### ISSUE THREAD

**Issue by kwertyops** [openlilylib/lilypond-export#30]
Using the example lilypond file from the README, and the following command:

```
lilypond -I ~/Code/openlilylib -V testlyexport.ly
```

Results in the following:

```
<snipped>
...
...
In unknown file:
           4 (ly:parse-string-expression #<Lily_parser #<Lily_lexer…> …)
In /private/tmp/lilypond-20230104-5751-ij2w8a/lilypond-2.24.0/out/share/lilypond/current/scm/lily/ly-syntax-constructors.scm:
    47:22  3 (music-function #<Music function #<procedure 107f8d4c0…> …)
In ice-9/eval.scm:
   293:34  2 (_ #(#(#(#(#<directory (lilypond-export api) …>) …) …) …))
   173:55  1 (_ #(#(#(#(#<directory (lilypond-export api) …>) …) …) …))
In ice-9/format.scm:
     52:8  0 (format "~A.~A" "testlyexport" "krn")

ice-9/format.scm:52:8: In procedure format:
format: bad destination `~a' "~A.~A"
```

**Comment by PaulMorris** [comment]
This looks like the following issue (from http://lilypond.org/doc/v2.24/Documentation/changes/index.html):

"The format function now requires a boolean or port as the first argument. This argument was optional in Guile 1.8. In order to make the function return the formatted output as a string, like format does without this argument in Guile 1.8, pass #f for this argument, i.e., (format #f "string" arguments …) instead of (format "string" arguments …)."

**Comment by kair0span** [comment]
Is some solution for this probem? I tried to run the example and run into the following error: Starting lilypond 2.24.4 [bach.ly]...
Processing `/var/folders/13/tf6n6x2x2nq6jz4tg18fg5bh0000gn/T/frescobaldi-jqmfhms9/tmpp579_tyb/bach.ly'
Parsing...

oll-core: library infrastructure successfully loaded.
[ice-9/format.scm:52:8](https://github.com/openlilylib/lilypond-export/issues/0): In procedure format:
format: bad destination `~A.~A'
Exited with return code 1.

**Comment by vpetzel** [comment]
This is caused by the missing destination in MusicXML.scm line 237

    (format "<clef-octave-change>~A</clef-octave-change>" (/ clefTransposition 7))

Support for this was deprecated with guile 2 and removed with 3. This particular thing should easily be fixed by replecing this by

    (format #f "<clef-octave-change>~A</clef-octave-change>" (/ clefTransposition 7))

But making this work with guile 3 and current lilypond might require more changes.

**Comment by kair0span** [comment]
@vpetzel The current stable version is using Guile 2.2 and not Guile 3.  I made the changes, that you suggested but the error still remains.

**Comment by vpetzel** [comment]
> [@vpetzel](https://github.com/vpetzel) The current stable version is using Guile 2.2 and not Guile 3. I made the changes, that you suggested but the error still remains.

Sorry, wrong section (although also a problem). (Also `#f`, not `#t`). This error comes from `api.scm` line 473, which again requires a `(format #f ...)`. It will make sense to batch search for `(format` calls and add `#f`.

**Comment by kair0span** [comment]
@vpetzel with you changes I was able to compile the example with lilypond 2.24.4. Thank you very much. However, the result was not satisfactory in comparison with the original lilypond file. The tool converts the .ly files in .xml and not in .musicxml files. Is it any difference between them?
